[package]
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
name = "pallet-parachain-info"
version = "0.1.0"

[dependencies]
codec = { package = "parity-scale-codec", version = "2.2", default-features = false, features = ["derive", "max-encoded-len"] }
serde = { version = "1.0.101", optional = true, features = ["derive"] }

frame-support = { git = "https://github.com/paritytech/substrate", rev = "09c016ba0a77f00a662dcd6ea76e5a5c777f31f4", default-features = false }
frame-system = { git = "https://github.com/paritytech/substrate", rev = "09c016ba0a77f00a662dcd6ea76e5a5c777f31f4", default-features = false }

cumulus-primitives-core = { git = "https://github.com/paritytech/cumulus", rev = "102a1d5428cd7acc4913d7d64cfba83fa35144dd", default-features = false }

[features]
default = ["std"]
std = [
	"codec/std",
	"serde",
	"cumulus-primitives-core/std",
	"frame-support/std",
	"frame-system/std",
]
