[profile.release]
panic = "unwind"

[workspace]
resolver = "2"
members = [
	"node",
	"parachains-common",
	"pallets/bridge",
	"pallets/bridge_transfer",
	"pallets/parachain-info",
	"runtime/khala",
]
