[profile.release]
panic = "unwind"

[workspace]
resolver = "2"

exclude = [
	"vendor/webpki",
	"vendor/ring",
	"polkadot/node/service"
]

members = [
	"node",
	"primitives",
	"crates/crypto",
	"crates/phala-mq",
	"crates/phala-rpc-ext",
	"crates/phala-types",
	"crates/trie-storage",
	"pallets/bridge",
	"pallets/bridge_transfer",
	"pallets/phala",
	"runtime/common",
	"runtime/khala",
]

[patch."https://github.com/paritytech/polkadot"]
polkadot-service = { path = "polkadot/node/service" }
