[profile.release]
panic = "unwind"

[workspace]
resolver = "2"

exclude = [
	"vendor/webpki",
	"vendor/ring",
]

members = [
	"node",
	"parachains-common",
	"crates/phala-types",
	"crates/phala-mq",
	"crates/phala-node-rpc-ext",
	"crates/prpc",
	"crates/phala-trie-storage",
	"pallets/phala",
	"pallets/phala/mq-runtime-api",
	"pallets/bridge",
	"pallets/bridge_transfer",
	"pallets/parachain-info",
	"runtime/khala",
]
