[profile.release]
panic = "unwind"
opt-level = 3

# make sure dev builds with backtrace do
# not slow us down
[profile.dev.package.backtrace]
inherits = "release"

[profile.production]
inherits = "release"
lto = true
codegen-units = 1

[profile.testnet]
inherits = "release"
debug = 1 # debug symbols are useful for profilers
debug-assertions = true
overflow-checks = true

[workspace]
resolver = "2"

exclude = [
	"vendor/webpki",
	"vendor/ring",
	"polkadot/node/service",
]

members = [
	"node",
	"parachains-common",
	"crates/phala-serde-more",
	"crates/phala-types",
	"crates/phala-mq",
	"crates/phala-node-rpc-ext",
	"crates/phala-node-rpc-ext/types",
	"crates/prpc",
	"crates/phala-trie-storage",
	"substrate/frame/utility",
	"pallets/phala",
	"pallets/phala/mq-runtime-api",
	"pallets/xtransfer",
	"pallets/parachain-info",
	"runtime/phala",
	"runtime/khala",
	"runtime/rhala",
	"runtime/thala",
	"runtime/shell",
]

[patch."https://github.com/paritytech/polkadot"]
polkadot-service = { path = "polkadot/node/service" }
