[profile.release]
panic = "unwind"

[workspace]
resolver = "2"

exclude = [
	"vendor/webpki",
	"vendor/ring",
	"polkadot/node/service",
	"substrate/client/network"
]

members = [
	"node",
	"parachains-common",
	"crates/phala-types",
	"crates/phala-mq",
	"crates/phala-node-rpc-ext",
	"crates/prpc",
	"crates/phala-trie-storage",
	"substrate/frame/utility",
	"pallets/phala",
	"pallets/phala/mq-runtime-api",
	"pallets/bridge",
	"pallets/bridge_transfer",
	"pallets/parachain-info",
	"runtime/khala",
]

[patch."https://github.com/paritytech/polkadot"]
polkadot-service = { path = "polkadot/node/service" }

[patch."https://github.com/paritytech/substrate"]
sc-network = { path = "substrate/client/network" }
