name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Cargo test
    runs-on: ubuntu-20.04
    steps:
      - name: Maximize build space # https://github.com/easimon/maximize-build-space
        uses: easimon/maximize-build-space@master
        with:
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2022-07-11
          override: true
          target: wasm32-unknown-unknown
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
      - name: Run cargo tests
        run: cargo test --verbose --workspace
