name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Cargo test
    runs-on: ubuntu-20.04
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master # https://github.com/easimon/maximize-build-space
        with:
          root-reserve-mb: 4096
          temp-reserve-mb: 4096
          remove-dotnet: "true"
          remove-android: "true"
          remove-haskell: "true"
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2022-07-11
          override: true
          target: wasm32-unknown-unknown
      - uses: actions/checkout@v3
        with:
          submodules: "true"
      - name: Build for Cargo test
        run: cargo test --no-run --verbose --workspace
      - name: Show disk usage
        run: df -h
      - name: Run Cargo test
        run: cargo test --verbose --workspace
